import json
import time
import random
from scratchclient import ScratchSession

print("program ran")

config = {
    "username": "MonkyTone",
    "password": "skmm6969",
    "sessionId": ".eJxVjrtuwzAMRf9Fc2qIsmRTGZMhXTLEKNB2MiSRrV0nkls7faDov1cGvGQgQNxzeMFfcZ34I7oLi604pjj8PKTIYiNad527doFtT5mBNCixNuqWeRcGjouwZBznPri5T7FYwVQ0PJ7XcLfKGzGnvOQjRuctEyEhauMDAhlXEqpKgkVF293-_fBIn81x_H4-Dfun-7ev5jBoi1bmmnN67eNdP-YmbQqNBZR5QN_-2LmpywZWZajAIL2EyrMMtQJEtEQMoWIPJRhVQ83i7x_KF1dw:1p4EwB:qsayLc7voXFcx74piJUZ4HJEHPU",
    "token": "e8ab9edd8d8845bc81d5a3d82601982d:BCqGWdvRMpxYQkCXHjwRGk49890"
}

username = config['username']
session_id = config["sessionId"]
token = config["token"]

session = ScratchSession("username", session_id=session_id, token=token)
currentIndex = 1

for p in session.get_front_page()["featured_projects"]:
    project = session.get_project(p)
    try:
        if project.comments_allowed == True:
            print("YES DADDDY!")
            project.post_comment(f"Can we apreciate how much effort {project.author.username} put into his project?\n\nthis is being generated by a bot. index: {currentIndex}")
            currentIndex += 1
            time.sleep(60)
    except:
        print("FAILED!")

